name: Hello World Workflow
on: [push]

jobs:
    run-shell:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World"
            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "NuGet Version: $(nuget help | grep Version)"
    
    macos-parallel-job:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers

    windows-dependent-job:
        runs-on: windows-latest
        needs: run-shell
        steps:
            - name: echo a string
              run: Write-Output "Windows String"